services:
  mqtt:
    container_name: mosquitto
    image: eclipse-mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mqtt/config:/mosquitto/config
      - ./mqtt/data:/mosquitto/data
      - ./mqtt/log:/mosquitto/log

  nodered:
    container_name: nodered
    image: nodered/node-red
    ports:
      - "1880:1880"
    volumes:
      - ./nodered/data:/data
  
  influxdb:
    container_name: influxdb
    image: influxdb:2.2.0
    ports:
      - "8086:8086"

  grafana:
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
networks:
  cdti:
    name: cdti
    driver: bridge